### ISSUE TITLE
Life Preserver: Replication: work in progress disappears

### ISSUE THREAD

**Issue by grahamperrin** [trueos/sysadm-ui-qt#1]
Whilst working towards a first replication, with an address in the host IP field, I turned away and worked for a short while at a different computer. 

When I looked back, SysAdm had lost sight of the Replication tab; instead there was the Schedules tab. 

Reproducible.

**Comment by beanpole135** [comment]
Can you give any more details about this?
I looked through the source code for the Life Preserver page, but there is no programmatic "tab change" calls used anywhere that I could find. Similarly, I have left a window open on the Replication tab (with the new replication options open) for quite a while now, and have not experienced any change in tabs/selections.

My guess would be that something on the system triggered a re-scan (was a replication going at the time?), or something else caused the UI to update.

**Comment by grahamperrin** [comment]
No replication (I was aiming to set up the first). 

A few days ago the problem occurred consistently, so I treated it as reproducible. 

Today, with the redesigned SysAdm client, I can't reproduce the problem. A first replication has been set up, and started.
