### ISSUE TITLE
Update Manager belongs under both application management and system management

### ISSUE THREAD

**Issue by grahamperrin** [trueos/sysadm-ui-qt#11]
Enhancement request. Is it possible for the manager to appear in both categories?

At the moment: _Application_ management tells us that the _System_ is up-to-date.

**Comment by kmoore134** [comment]
Ken, I would leave this in System Management, but make sure the Application manager shows some sort of "updates avail" notice that takes you over there when clicked.

**Comment by q5sys** [comment]
Housecleaning time.  Many changes have occurred so I'm closing old tickets. If the issue still remains we can reopen.
