### ISSUE TITLE
Update Manager should offer (maybe link to) details of an update before the user chooses to apply that update 

### ISSUE THREAD

**Issue by grahamperrin** [trueos/sysadm-ui-qt#14]
Enhancement request. 

With SysAdm as is, selecting an update reveals no additional information; there's just the name/identifier. 

This area of the GUI might be a good place to link to (or represent relevant content from) https://raw.githubusercontent.com/trueos/trueos-changelog/master/CHANGELOG

**Comment by grahamperrin** [comment]
Additionally: if an update will completely **remove** any item, it will be good to make that fact unmistakably clear. (Minimise the risk of unwanted post-update surprises.)

Long-term, I guess that some improvement could be made to order of output from `pc-updatemanager`. In the meantime, maybe a grep for the word _removed_ could allow the SysAdm UI to forewarn that a removal should be expected.

**Comment by q5sys** [comment]
Housecleaning time.  Many changes have occurred so I'm closing old tickets. If the issue still remains we can reopen.
