### ISSUE TITLE
Consistent use of the word 'pool' (never zpool to describe a pool)

### ISSUE THREAD

**Issue by grahamperrin** [trueos/sysadm-ui-qt#15]
Under the Schedules tab of Life Preserver, one of the headings is _Zpool_. That **should** be _Pool_. 

Under the Snapshots tab, there's the phrase _ZFS Pool_. That might be simplified to _Pool_. 

And so on … if I find more examples, I'll add to this issue.

**Comment by q5sys** [comment]
Housecleaning time.  Many changes have occurred so I'm closing old tickets. If the issue still remains we can reopen.
