### ISSUE TITLE
Life Preserver: Replication: ambiguity between 'Start' and 'Initialise' 

### ISSUE THREAD

**Issue by grahamperrin** [trueos/sysadm-ui-qt#16]
… or 'Initialize', for you crazy Americans :)

Either way, there's ambiguity and a visit to the handbook should be unnecessary. 

What might be a better word for one of the two? Maybe 'Reinitialise'? 

There's a small, indistinct circular icon on one of the two clouds, if I look closely I see that the circle comprises two arrows. To a Mac user, that's reminiscent of Time Machine (or sync; Apple often misused the sync icon (clockwise) in a Time Machine context (where arrows should have been counterclockwise)).

**Comment by grahamperrin** [comment]
Later, I noticed the status bar. 

For the _Initialize_ button, the status bar uses the word _Re-initialize_.  

Things become less ambiguous (and IMHO the status bar is sometimes not an ideal place for hints; I'll take this opinion to the testing list). 

Please rename the button. A better phrase might be: 

**Discard backup**

**Comment by q5sys** [comment]
Housecleaning time.  Many changes have occurred so I'm closing old tickets. If the issue still remains we can reopen.
