### ISSUE TITLE
AppCafe: clicking a listed item should select that item

### ISSUE THREAD

**Issue by grahamperrin** [trueos/sysadm-ui-qt#17]
Click Installed, then click one of the names. 

**Expected**

Selection of the line (e.g. a change from black text on the white background, to white text on a blue background (should I say 'highlight' or 'focus' instead of selection?))

– and simple selection should neither check, nor clear a check from, the box in the Status column. 

**Actual result**

Disappearance of the list, presentation of a row of tabs with a tag/label icon in the first tab.

**Comment by beanpole135** [comment]
I am unable to reproduce this on the current version of the AppCafe.
Clicking on an item in the installed tab just highlights the item (does not change the checked state), nor does it change the list around at all.
