### ISSUE TITLE
AppCafe item information: clicking 'Back' takes the user too far back

### ISSUE THREAD

**Issue by grahamperrin** [trueos/sysadm-ui-qt#19]
After viewing information for a listed/highlighted item, click _Back_.

**Expected**

The list, with the line (or multiple lines) still highlighted. 

**Actual result**

Too far back: the _Browse_ tab. After which the user must again click _Installed_ to review what was truly one step back. 

Before attending to this issue, I suggest priority to #17.

**Comment by beanpole135** [comment]
Fixed!
https://github.com/trueos/sysadm-ui-qt/commit/d19c9b8382571857117826859df2c22d742f814a
