### ISSUE TITLE
Life Preserver: Snapshots: pool selected, selection is lost

### ISSUE THREAD

**Issue by grahamperrin** [trueos/sysadm-ui-qt#2]
Consequent to https://github.com/trueos/sysadm-ui-qt/issues/1 I clicked the Snapshots tab and found that the previously selected pool was no longer selected.

**Comment by beanpole135** [comment]
Close this issue as a duplicate to #1. If something did trigger a re-scan/update of the UI that would most likely clear the current selections as well.
