### ISSUE TITLE
SysAdm should alert the user when Life Preserver fails

### ISSUE THREAD

**Issue by grahamperrin** [trueos/sysadm-ui-qt#23]
Not a nagging alert, but there should be at least an unmistakable exclamation mark in lieu of (or overlaying) the SysAdm icon. 

Yellow alert for anything that requires non-urgent attention. 

Red alert when urgent attention is appropriate.

**Comment by q5sys** [comment]
Housecleaning time.  Many changes have occurred so I'm closing old tickets. If the issue still remains we can reopen.
