### ISSUE TITLE
User Manager field for 'User Name' allows characters that must be disallowed

### ISSUE THREAD

**Issue by grahamperrin** [trueos/sysadm-ui-qt#24]
For example: _Joe Bloggs_

If a user is added with that username then User Manager shows: 

Joe (User &) 
User Name Joe
Full Name User &
Home Dir Path /home/Joe

**Comment by beanpole135** [comment]
Fixed!

https://github.com/trueos/sysadm-ui-qt/commit/76d988d4056ab56b2459af899ec0ffbe2cd18b62
