### ISSUE TITLE
User Manager: password entered but 'Save' does not save the password to /etc/master.passwd

### ISSUE THREAD

**Issue by grahamperrin** [trueos/sysadm-ui-qt#26]
Maybe a consequence of #25. 

I realised this bug whilst troubleshooting apparent rejection of credentials for a PersonaCrypt login.

Multiple GUI-based attempts to set/save the password did not work around the rejections. Eventually, 

`sudo cat /etc/master.passwd`

– I realised that there was no hash in the line for the affected user. 

AFAIR I worked around the problem by **overtyping in the full name field** (to work around the disappearance of my surname, _Perrin_) with 'GrahamPerrin' **and then** retyping my password **and then** tabbing beyond the password field and finally clicking 'Save'.

**Comment by beanpole135** [comment]
Fixed last week.
