### ISSUE TITLE
User Manager: /home/ not consistent with /usr/home/

### ISSUE THREAD

**Issue by grahamperrin** [trueos/sysadm-ui-qt#30]
Consistency of appearance. 

During a (first run) setup of TrueOS Desktop it's necessary to add a non-root user, and for that first user the base path for the home is: 

`/usr/home/`

I understand that with the symlink at the root `/` of the file system, `home -> /usr/home`

Still, the visual inconsistency is not ideal. On more than one occasion I wondered whether the terse path was amongst the causes of PersonaCrypt not working as expected in a clean installation of the OS.

**Comment by q5sys** [comment]
Housecleaning time.  Many changes have occurred so I'm closing old tickets. If the issue still remains we can reopen.
