### ISSUE TITLE
SysAdm: previously disclosed categories should not be closed in response to 'Back'

### ISSUE THREAD

**Issue by grahamperrin** [trueos/sysadm-ui-qt#32]
SysAdm is much improved :+1: but still, there's the repeated, frequent annoyance of premature closure of things that were disclosed. 

For example: if a user discloses all categories before using Life Preserver, then a click on the back arrow should not close all those things. 

Repeated reopening/disclosing is tedious, and having the phrase `Control Panel` alongside the back arrow does not reduce the annoyance of the unexpected, undesirable result of a click on that arrow.

**Comment by tigersharke** [comment]
I agree, one would expect to "start from scratch/default" when an application is quit, but in the course of using one, opening/closing of things should remain as last used- particularly when that action or series of actions would be tedious.

**Comment by beanpole135** [comment]
This was fixed last week - now going "back" to the control panel will automatically expand/highlight item as needed so the last-used page is highlighted and visible.
