### ISSUE TITLE
pc-mixer should grey out PulseAudio settings if not installed

### ISSUE THREAD

**Issue by dlavigne** [trueos/sysadm-ui-qt#4]
Since Pulseaudio is no longer installed by default, it is confusing to the user to have these options do nothing upon click. Either having them greyed out or providing a helpful message on click that pulseaudio needs to be installed using AppCafe would alleviate this confusion.

**Comment by beanpole135** [comment]
Done!

https://github.com/trueos/pc-mixer/commit/b330596c3d9473605d0febea20a19edb6324192f
