### ISSUE TITLE
Date is ambiguous in Update Manager

### ISSUE THREAD

**Issue by kmoore134** [trueos/sysadm-ui-qt#5]
_From @dlavigne on August 11, 2016 17:53_

See attached screenshot for an example. Depending upon where you live in the world, the last check either occurred on Aug 11 or Nov 8. Specifically stating the month name would make this clear.
![update1](https://cloud.githubusercontent.com/assets/486100/17598921/bfa3905e-5fca-11e6-93e4-24015e236427.png)

_Copied from original issue: trueos/trueos-utils-qt5#4_

**Comment by beanpole135** [comment]
Fixed!
I just changed it from the short date format to the long date format for the users current locale.
