### ISSUE TITLE
Allow the user to tell whether a Life Preserver replication is running

### ISSUE THREAD

**Issue by grahamperrin** [trueos/sysadm-ui-qt#8]
Enhancement request. 

As a workaround, I have open a terminal window with an ssh connection to FreeNAS, running – 

`zpool iostat tallhalf 5`

– where _tallhalf_ is the name of the pool that includes the dataset.

**Comment by q5sys** [comment]
Housecleaning time.  Many changes have occurred so I'm closing old tickets. If the issue still remains we can reopen.
